# Generated by Django 3.1.7 on 2021-10-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termoapp', '0002_t_sbp_dbp_s_br'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_sbp_dbp_s_br',
            name='sex',
            field=models.TextField(blank=True, max_length=10, verbose_name='Пол'),
        ),
    ]
